### ISSUE TITLE
help :) i got error 1

### ISSUE THREAD

**Issue by sardina00** [idc/libftps4#3]
build/ftps4.o: In function `send_LIST':
ftps4.c:(.text+0x17e0): undefined reference to `time'
ftps4.c:(.text+0x1ef9): undefined reference to `readlink'
collect2: error: ld returned 1 exit status
Makefile:25: recipe for target 'libftps4-master.bin' failed
make: *** [libftps4-master.bin] Error 1

**Comment by idc** [comment]
Use my fork of the SDK.

**Comment by sardina00** [comment]
thank you sir )))  super !
